const fs = require('fs');
const lines = fs.readFileSync('app.js', 'utf8').split('\n');
const goodLines = lines.slice(0, 7110);
goodLines.push('}');
goodLines.push('');
goodLines.push('function sendPartnerApprovalNotification(rest) {');
goodLines.push('  const content = document.getElementById(\'mockNotificationContent\');');
goodLines.push('  const vendorLink = window.location.origin + window.location.pathname + \'?vendor=true\';');
goodLines.push('  ');
goodLines.push('  content.innerHTML = `');
goodLines.push('    <div style="font-size: 13px; color: var(--text-main); margin-bottom: 12px;">');
goodLines.push('      <b>To:</b> ${rest.email || \'Partner\'}<br>');
goodLines.push('      <b>Subject:</b> Congratulations! Your FoodBank Partnership is Approved 🎉');
goodLines.push('    </div>');
goodLines.push('    <div style="background: var(--bg-card); padding: 12px; border-radius: 8px; border: 1px solid var(--border); font-size: 13px;">');
goodLines.push('      <p>Hi <b>${rest.name}</b>,</p>');
goodLines.push('      <p>Your KYC and registration documents have been verified and approved by the FoodBank Admin team.</p>');
goodLines.push('      <p>You can now log in to the Vendor Portal to manage your menu, track orders, and view payouts.</p>');
goodLines.push('      <div style="margin: 16px 0;">');
goodLines.push('        <a href="${vendorLink}" target="_blank" style="display:inline-block; background: #2563eb; color: #fff; padding: 10px 16px; border-radius: 6px; text-decoration: none; font-weight: 700;">Open Vendor App</a>');
goodLines.push('      </div>');
goodLines.push('      <p>Commission Rate: <b>${rest.commissionRate}%</b></p>');
goodLines.push('      <p>Welcome aboard!<br>- FoodBank Team</p>');
goodLines.push('    </div>');
goodLines.push('  `;');
goodLines.push('  ');
goodLines.push('  openModal(\'mockNotificationModal\');');
goodLines.push('}');
goodLines.push('');
fs.writeFileSync('app.js', goodLines.join('\n'));
